#include <Engine/FX/FireFX.hpp>
#include <Engine/FX/PlasmaUpFX.hpp>
#include <Engine/FX/PlasmaFX.hpp>
#include <Engine/FX/MoireFX.hpp>
#include <Engine/FX/MoireTimedFX.hpp>
#include <Engine/FX/MoireExtendFX.hpp>
#include <Engine/FX/BlobsFX.hpp>
#include <Engine/FX/SpriteFX.hpp>
#include <Engine/FX/FireUpDownFX.hpp>